[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://web-production-af821.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
